version: "3.7"

services:
  backend:
    image: ghcr.io/mmolenda/missalemeum/backend:latest
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - PDF_CACHE_DIR=/app/.cache/pdf
      - PDF_CACHE_SIZE_BYTES=1000000000
    volumes:
      - missalemeum-pdf-cache:/app/.cache/pdf

  frontend:
    image: ghcr.io/mmolenda/missalemeum/frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "8081:8081"
    environment:
      - API_URL=http://backend:8080
    networks:
      - app-network
    depends_on:
      - backend

  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - backend
      - frontend

networks:
  app-network:
    driver: bridge

volumes:
  missalemeum-pdf-cache:
