from typing import List

from api.constants import common as constants

# Pages in paper missal/s


def get_pages(angelus: int, lasance: int, baronius: int) -> List[str]:
    return [
        f"Angelus Press p. {angelus}",
        f"Father Lasance p. {lasance}",
        f"Baronius Press p. {baronius}",
    ]


PAGES = {
    constants.TEMPORA_EPI1_0: [],  # 'The Holy Family: Jesus, Mary & Joseph',
    constants.TEMPORA_EPI2_0: [],  # 'II Sunday after Epiphany',
    constants.TEMPORA_EPI3_0: [],  # 'III Sunday after Epiphany',
    constants.TEMPORA_EPI4_0: [],  # 'IV Sunday after Epiphany',
    constants.TEMPORA_EPI5_0: [],  # 'V Sunday after Epiphany',
    constants.TEMPORA_EPI6_0: [],  # 'VI Sunday after Epiphany',
    constants.TEMPORA_QUADP1_0: [],  # 'Septuagesima Sunday',
    constants.TEMPORA_QUADP2_0: [],  # 'Sexagesima Sunday',
    constants.TEMPORA_QUADP3_0: [],  # 'Quinquagesima Sunday',
    constants.TEMPORA_QUADP3_3: [],  # 'Ash Wednesday',
    constants.TEMPORA_QUADP3_4: [],  # 'Feria V after Ash Wednesday',
    constants.TEMPORA_QUADP3_5: [],  # 'Feria VI after Ash Wednesday',
    constants.TEMPORA_QUADP3_6: [],  # 'Saturday after Ash Wednesday',
    constants.TEMPORA_QUAD1_0: [],  # 'I Sunday of Lent',
    constants.TEMPORA_QUAD1_1: [],  # 'Feria II after the I Sunday of Lent',
    constants.TEMPORA_QUAD1_2: [],  # 'Feria III after the I Sunday of Lent',
    constants.TEMPORA_QUAD1_3: [],  # 'Ember Wednesday of Lent',
    constants.TEMPORA_QUAD1_4: [],  # 'Feria V after the I Sunday of Lent',
    constants.TEMPORA_QUAD1_5: [],  # 'Ember Friday of Lent',
    constants.TEMPORA_QUAD1_6: [],  # 'Ember Saturday of Lent',
    constants.TEMPORA_QUAD2_0: [],  # 'II Sunday of Lent',
    constants.TEMPORA_QUAD2_1: [],  # 'Feria II after the II Sunday of Lent',
    constants.TEMPORA_QUAD2_2: [],  # 'Feria III after the II Sunday of Lent',
    constants.TEMPORA_QUAD2_3: [],  # 'Feria IV after the II Sunday of Lent',
    constants.TEMPORA_QUAD2_4: [],  # 'Feria V after the II Sunday of Lent',
    constants.TEMPORA_QUAD2_5: [],  # 'Feria VI after the II Sunday of Lent',
    constants.TEMPORA_QUAD2_6: get_pages(353, 283, 369),  # 'Saturday after the II Sunday of Lent',
    constants.TEMPORA_QUAD3_0: get_pages(359, 294, 377),  # 'III Sunday of Lent',
    constants.TEMPORA_QUAD3_1: get_pages(363, 294, 380),  # 'Feria II after the III Sunday of Lent',
    constants.TEMPORA_QUAD3_2: get_pages(368, 303, 385),  # 'Feria III after the III Sunday of Lent',
    constants.TEMPORA_QUAD3_3: [],  # 'Feria IV after the III Sunday of Lent',
    constants.TEMPORA_QUAD3_4: [],  # 'Feria V after the III Sunday of Lent',
    constants.TEMPORA_QUAD3_5: [],  # 'Feria VI after the III Sunday of Lent',
    constants.TEMPORA_QUAD3_6: [],  # 'Saturday after the III Sunday of Lent',
    constants.TEMPORA_QUAD4_0: [],  # 'IV Sunday of Lent',
    constants.TEMPORA_QUAD4_1: [],  # 'Feria II after the IV Sunday of Lent',
    constants.TEMPORA_QUAD4_2: [],  # 'Feria III after the IV Sunday of Lent',
    constants.TEMPORA_QUAD4_3: [],  # 'Feria IV after the IV Sunday of Lent',
    constants.TEMPORA_QUAD4_4: [],  # 'Feria V after the IV Sunday of Lent',
    constants.TEMPORA_QUAD4_5: [],  # 'Feria VI after the IV Sunday of Lent',
    constants.TEMPORA_QUAD4_6: [],  # 'Saturday after the IV Sunday of Lent',
    constants.TEMPORA_QUAD5_0: [],  # 'Passion Sunday',
    constants.TEMPORA_QUAD5_1: [],  # 'Feria II of Passion Week',
    constants.TEMPORA_QUAD5_2: [],  # 'Feria III of Passion Week',
    constants.TEMPORA_QUAD5_3: [],  # 'Feria IV of Passion Week',
    constants.TEMPORA_QUAD5_4: [],  # 'Feria V of Passion Week',
    constants.TEMPORA_QUAD5_5: [],  # 'Feria VI of Passion Week',
    constants.TEMPORA_QUAD5_6: [],  # 'Saturday of Passion Week',
    constants.TEMPORA_QUAD6_0: [],  # 'Palm Sunday',
    constants.TEMPORA_QUAD6_1: [],  # 'Feria II of Holy Week',
    constants.TEMPORA_QUAD6_2: [],  # 'Feria III of Holy Week',
    constants.TEMPORA_QUAD6_3: [],  # 'Feria IV of Holy Week',
    constants.TEMPORA_QUAD6_4: [],  # 'Holy Thursday',
    constants.TEMPORA_QUAD6_5: [],  # 'Good Friday',
    constants.TEMPORA_QUAD6_6: [],  # 'Holy Saturday',
    constants.TEMPORA_PASC0_0: [],  # 'Easter Sunday',
    constants.TEMPORA_PASC0_1: [],  # 'Monday in the Octave of Easter',
    constants.TEMPORA_PASC0_2: [],  # 'Tuesday in the Octave of Easter',
    constants.TEMPORA_PASC0_3: [],  # 'Wednesday in the Octave of Easter',
    constants.TEMPORA_PASC0_4: [],  # 'Thursday in the Octave of Easter',
    constants.TEMPORA_PASC0_5: [],  # 'Friday in the Octave of Easter',
    constants.TEMPORA_PASC0_6: [],  # 'Saturday in the Octave of Easter',
    constants.TEMPORA_PASC1_0: [],  # 'Low Sunday',
    constants.TEMPORA_PASC2_0: [],  # 'II Sunday after Easter',
    constants.TEMPORA_PASC3_0: [],  # 'III Sunday after Easter',
    constants.TEMPORA_PASC4_0: [],  # 'IV Sunday after Easter',
    constants.TEMPORA_PASC5_0: [],  # 'V Sunday after Easter',
    constants.TEMPORA_PASC5_1: [],  # 'The Minor Litanies – Rogations',
    constants.TEMPORA_PASC5_2: [],  # 'The Minor Litanies – Rogations',
    constants.TEMPORA_PASC5_3: [],  # 'Vigil of the Ascension',
    constants.TEMPORA_PASC5_4: [],  # 'Ascension of the Lord',
    constants.TEMPORA_PASC6_0: [],  # 'Sunday after the Ascension',
    constants.TEMPORA_PASC6_6: [],  # 'Pentecost Vigil',
    constants.TEMPORA_PASC7_0: [],  # 'Pentecost Sunday',
    constants.TEMPORA_PASC7_1: [],  # 'Monday after Pentecost',
    constants.TEMPORA_PASC7_2: [],  # 'Tuesday after Pentecost',
    constants.TEMPORA_PASC7_3: [],  # 'Ember Wednesday of Pentecost',
    constants.TEMPORA_PASC7_4: [],  # 'Thursday after Pentecost',
    constants.TEMPORA_PASC7_5: [],  # 'Ember Friday of Pentecost',
    constants.TEMPORA_PASC7_6: [],  # 'Ember Saturday of Pentecost',
    constants.TEMPORA_PENT01_0: [],  # 'Trinity Sunday',
    constants.TEMPORA_PENT01_4: [],  # 'Corpus Christi',
    constants.TEMPORA_PENT02_0: [],  # 'II Sunday after Pentecost',
    constants.TEMPORA_PENT02_5: [],  # 'Sacred Heart of Jesus',
    constants.TEMPORA_PENT03_0: [],  # 'III Sunday after Pentecost',
    constants.TEMPORA_PENT04_0: [],  # 'IV Sunday after Pentecost',
    constants.TEMPORA_PENT05_0: [],  # 'V Sunday after Pentecost',
    constants.TEMPORA_PENT06_0: [],  # 'VI Sunday after Pentecost',
    constants.TEMPORA_PENT07_0: [],  # 'VII Sunday after Pentecost',
    constants.TEMPORA_PENT08_0: [],  # 'VIII Sunday after Pentecost',
    constants.TEMPORA_PENT09_0: [],  # 'IX Sunday after Pentecost',
    constants.TEMPORA_PENT10_0: [],  # 'X Sunday after Pentecost',
    constants.TEMPORA_PENT11_0: [],  # 'XI Sunday after Pentecost',
    constants.TEMPORA_PENT12_0: [],  # 'XII Sunday after Pentecost',
    constants.TEMPORA_PENT13_0: [],  # 'XIII Sunday after Pentecost',
    constants.TEMPORA_PENT14_0: [],  # 'XIV Sunday after Pentecost',
    constants.TEMPORA_PENT15_0: [],  # 'XV Sunday after Pentecost',
    constants.TEMPORA_PENT16_0: [],  # 'XVI Sunday after Pentecost',
    constants.TEMPORA_PENT17_0: [],  # 'XVII Sunday after Pentecost',
    constants.TEMPORA_PENT18_0: [],  # 'XVIII Sunday after Pentecost',
    constants.TEMPORA_PENT19_0: [],  # 'XIX Sunday after Pentecost',
    constants.TEMPORA_PENT20_0: [],  # 'XX Sunday after Pentecost',
    constants.TEMPORA_PENT21_0: [],  # 'XXI Sunday after Pentecost',
    constants.TEMPORA_PENT22_0: [],  # 'XXII Sunday after Pentecost',
    constants.TEMPORA_PENT23_0: [],  # 'XXIII Sunday after Pentecost',
    constants.TEMPORA_PENT_3: [],  # 'Ember Wednesday of September',
    constants.TEMPORA_PENT_5: [],  # 'Ember Friday of September',
    constants.TEMPORA_PENT_6: [],  # 'Ember Saturday of September',
    constants.TEMPORA_PENT24_0: [],  # 'XXIV Sunday after Pentecost',
    constants.TEMPORA_ADV1_0: [],  # 'I Sunday of Advent',
    constants.TEMPORA_ADV2_0: [],  # 'II Sunday of Advent',
    constants.TEMPORA_ADV3_0: [],  # 'III Sunday of Advent',
    constants.TEMPORA_ADV3_3: [],  # 'Ember Wednesday of Advent',
    constants.TEMPORA_ADV3_5: [],  # 'Ember Friday of Advent',
    constants.TEMPORA_ADV3_6: [],  # 'Ember Saturday of Advent',
    constants.TEMPORA_ADV4_0: [],  # 'IV Sunday of Advent',
    constants.TEMPORA_NAT1_0: [],  # 'Sunday in the Octave of Christmas',
    constants.TEMPORA_NAT1_1: [],  # 'Feria in the Octave of Christmas',
    constants.TEMPORA_NAT2_0: [],  # 'Holy Name of Jesus',
    constants.SANCTI_10_DU: [],  # 'Christ the King',
    constants.TEMPORA_EPI1_0A: [],  # 'Sunday after Epiphany',
    constants.TEMPORA_PENT01_0A: [],  # 'Sunday after Pentecost',
    constants.TEMPORA_C_10A: [],  # 'I Mass of the B. V. M. – Rorate',
    constants.TEMPORA_C_10B: [],  # 'II Mass of the B. V. M. – Vultum Tuum',
    constants.TEMPORA_C_10C: [],  # 'III Mass of the B. V. M. – Salve, Sancta Parens',
    constants.TEMPORA_C_10PASC: [],  # 'IV Mass of the B. V. M. – Salve, Sancta Parens',
    constants.TEMPORA_C_10T: [],  # 'V Mass of the B. V. M. – Salve, Sancta Parens',
    constants.COMMUNE_C_10A: [],  # 'I Mass of the B. V. M. – Rorate',
    constants.COMMUNE_C_10B: [],  # 'II Mass of the B. V. M. – Vultum Tuum',
    constants.COMMUNE_C_10C: [],  # 'III Mass of the B. V. M. – Salve, Sancta Parens',
    constants.COMMUNE_C_10PASC: [],  # 'IV Mass of the B. V. M. – Salve, Sancta Parens',
    constants.COMMUNE_C_10T: [],  # 'V Mass of the B. V. M. – Salve, Sancta Parens',
    constants.SANCTI_01_01: [],  # 'Octave Day of Christmas',
    constants.SANCTI_01_06: [],  # 'Epiphany of the Lord',
    constants.SANCTI_01_13: [],  # 'Commemoration of the Baptism of the Lord',
    constants.SANCTI_01_14: [],  # 'St. Hilary',
    constants.SANCTI_01_15: [],  # 'St. Paul, the First Hermit',
    constants.SANCTI_01_16: [],  # 'St. Marcellus I',
    constants.SANCTI_01_17: [],  # 'St. Anthony',
    constants.SANCTI_01_18: [],  # 'St. Prisca',
    constants.SANCTI_01_19: [],  # 'Sts. Marius, Martha, Audifax & Abachum',
    constants.SANCTI_01_20: [],  # 'Sts. Fabian & Sebastian',
    constants.SANCTI_01_21: [],  # 'St. Agnes',
    constants.SANCTI_01_22: [],  # 'Sts. Vincent & Anastasius ',
    constants.SANCTI_01_23: [],  # 'St. Raymond of Peñafort',
    constants.SANCTI_01_24: [],  # 'St. Timothy',
    constants.SANCTI_01_25: [],  # 'Conversion of St. Paul',
    constants.SANCTI_01_26: [],  # 'St. Polycarp',
    constants.SANCTI_01_27: [],  # 'St. John Chrysostom',
    constants.SANCTI_01_28: [],  # 'St. Peter Nolasco',
    constants.SANCTI_01_29: [],  # 'St. Francis de Sales',
    constants.SANCTI_01_30: [],  # 'St. Martina',
    constants.SANCTI_01_31: [],  # 'St. John Bosco',
    constants.SANCTI_02_01: [],  # 'St. Ignatius of Antioch',
    constants.SANCTI_02_02: [],  # 'Purification of the Blessed Virgin Mary',
    constants.SANCTI_02_03: [],  # 'St. Blaise',
    constants.SANCTI_02_04: [],  # 'St. Andrew Corsini',
    constants.SANCTI_02_05: [],  # 'St. Agatha',
    constants.SANCTI_02_06: [],  # 'St. Titus',
    constants.SANCTI_02_07: [],  # 'St. Romuald ',
    constants.SANCTI_02_08: [],  # 'St. John of Matha',
    constants.SANCTI_02_09: [],  # 'St. Cyril of Alexandria',
    constants.SANCTI_02_10: [],  # 'St. Scholastica',
    constants.SANCTI_02_11: [],  # 'Our Lady of Lourdes',
    constants.SANCTI_02_12: [],  # 'Seven Holy Servite Founders',
    constants.SANCTI_02_14: [],  # 'St. Valentine',
    constants.SANCTI_02_15: [],  # 'Sts. Faustinus & Jovita',
    constants.SANCTI_02_18: [],  # 'St. Simeon',
    constants.SANCTI_02_22: [],  # 'Chair of St. Peter ',
    constants.SANCTI_02_23: [],  # 'St. Peter Damien',
    constants.SANCTI_02_24: [],  # 'St. Matthias',
    constants.SANCTI_02_27: [],  # 'St. Gabriel of Our Lady of Sorrows',
    constants.SANCTI_03_04: [],  # 'St. Casimir',
    constants.SANCTI_03_06: [],  # 'Sts. Felicitas & Perpetua',
    constants.SANCTI_03_07: [],  # 'St. Thomas Aquinas',
    constants.SANCTI_03_08: [],  # 'St. John of God',
    constants.SANCTI_03_09: [],  # 'St. Frances Rome',
    constants.SANCTI_03_10: [],  # 'Forty Holy Martyrs of Sebaste',
    constants.SANCTI_03_12: [],  # 'St. Gregory the Great',
    constants.SANCTI_03_17: [],  # 'St. Patrick',
    constants.SANCTI_03_18: [],  # 'St. Cyril of Jerusalem',
    constants.SANCTI_03_19: [],  # 'St. Joseph, Spouse of the Bl. Virgin Mary',
    constants.SANCTI_03_21: [],  # 'St. Benedict',
    constants.SANCTI_03_24: [],  # 'St. Gabriel the Archangel',
    constants.SANCTI_03_25: [],  # 'Annunciation of the Blessed Virgin Mary',
    constants.SANCTI_03_27: [],  # 'St. John Damascene',
    constants.SANCTI_03_28: [],  # 'St. John of Capistrano',
    constants.SANCTI_04_02: [],  # 'St. Francis of Paola',
    constants.SANCTI_04_04: [],  # 'St. Isidore of Seville',
    constants.SANCTI_04_05: [],  # 'St. Vincent Ferrer',
    constants.SANCTI_04_11: [],  # 'St. Leo the Great',
    constants.SANCTI_04_13: [],  # 'St. Hermenegild',
    constants.SANCTI_04_14: [],  # 'St. Justin',
    constants.SANCTI_04_17: [],  # 'St. Anicetus',
    constants.SANCTI_04_21: [],  # 'St. Anselm',
    constants.SANCTI_04_22: [],  # 'Sts. Soter & Caius',
    constants.SANCTI_04_23: [],  # 'St. George',
    constants.SANCTI_04_24: [],  # 'St. Fidelis of Sigmaringen',
    constants.SANCTI_04_25: [],  # 'St. Mark',
    constants.SANCTI_04_26: [],  # 'Sts. Cletus & Marcellinus',
    constants.SANCTI_04_27: [],  # 'St. Peter Canisius',
    constants.SANCTI_04_28: [],  # 'St. Paul of the Cross',
    constants.SANCTI_04_29: [],  # 'St. Peter of Verona',
    constants.SANCTI_04_30: [],  # 'St. Catherine of Siena',
    constants.SANCTI_05_01: [],  # 'St. Joseph the Workman',
    constants.SANCTI_05_02: [],  # 'St. Athanasius ',
    constants.SANCTI_05_03: [],  # 'Sts. Alexander & Companions',
    constants.SANCTI_05_04: [],  # 'St. Monica ',
    constants.SANCTI_05_05: [],  # 'St. Pius V',
    constants.SANCTI_05_07: [],  # 'St. Stanislaus',
    constants.SANCTI_05_09: [],  # 'St. Gregory of Nazianzen',
    constants.SANCTI_05_10: [],  # 'St. Antoninus',
    constants.SANCTI_05_11: [],  # 'Sts. Philip & James',
    constants.SANCTI_05_12: [],  # 'Sts. Nereus, Achilleus, Domitilla, & Pancras',
    constants.SANCTI_05_13: [],  # 'St. Robert Bellarmine',
    constants.SANCTI_05_14: [],  # 'St. Boniface',
    constants.SANCTI_05_15: [],  # 'St. John Baptist de la Salle',
    constants.SANCTI_05_16: [],  # 'St. Ubaldus',
    constants.SANCTI_05_17: [],  # 'St. Paschal Baylon',
    constants.SANCTI_05_18: [],  # 'St. Venantius',
    constants.SANCTI_05_19: [],  # 'St. Peter Celestine',
    constants.SANCTI_05_20: [],  # 'St. Bernardine of Siena',
    constants.SANCTI_05_25: [],  # 'St. Gregory VII',
    constants.SANCTI_05_26: [],  # 'St. Philip Neri',
    constants.SANCTI_05_27: [],  # 'St. Bede the Venerable ',
    constants.SANCTI_05_28: [],  # 'St. Augustine of Canterbury',
    constants.SANCTI_05_29: [],  # 'St. Mary Magdalene de Pazzi',
    constants.SANCTI_05_30: [],  # 'St. Felix I',
    constants.SANCTI_05_31: [],  # 'Queenship of the Blessed Virgin Mary',
    constants.SANCTI_06_01: [],  # 'St. Angela Merici ',
    constants.SANCTI_06_02: [],  # 'Sts. Marcellinus, Peter, & Erasmus ',
    constants.SANCTI_06_04: [],  # 'St. Francis Caracciolo',
    constants.SANCTI_06_05: [],  # 'St. Boniface',
    constants.SANCTI_06_06: [],  # 'St. Norbert',
    constants.SANCTI_06_09: [],  # 'Sts. Primus & Felicianus',
    constants.SANCTI_06_10: [],  # 'St. Margaret of Scotland',
    constants.SANCTI_06_11: [],  # 'St. Barnabas',
    constants.SANCTI_06_12: [],  # 'St. John of San Fecundo',
    constants.SANCTI_06_13: [],  # 'St. Anthony of Padua',
    constants.SANCTI_06_14: [],  # 'St. Basil the Great',
    constants.SANCTI_06_15: [],  # 'St. Vitus',
    constants.SANCTI_06_17: [],  # 'St. Gregory Barbarigo',
    constants.SANCTI_06_18: [],  # 'St. Ephrem of Syria',
    constants.SANCTI_06_19: [],  # 'St. Julia of Falconieri',
    constants.SANCTI_06_20: [],  # 'St. Silverius',
    constants.SANCTI_06_21: [],  # 'St. Aloysius Gongzaga',
    constants.SANCTI_06_22: [],  # 'St. Paulinus of Nola',
    constants.SANCTI_06_23: [],  # 'Vigil of the Nativity of St. John the Baptist',
    constants.SANCTI_06_24: [],  # 'Nativity of St. John the Baptist',
    constants.SANCTI_06_25: [],  # 'St. William',
    constants.SANCTI_06_26: [],  # 'Sts. John & Paul',
    constants.SANCTI_06_28: [],  # 'Vigil of Sts. Peter & Paul',
    constants.SANCTI_06_29: [],  # 'Sts. Peter & Paul',
    constants.SANCTI_06_30: [],  # 'In Commemoratione Sancti Pauli Apostoli',
    constants.SANCTI_07_01: [],  # 'The Precious Blood of Our Lord Jesus Christ',
    constants.SANCTI_07_02: [],  # 'Visitation of the Blessed Virgin Mary',
    constants.SANCTI_07_03: [],  # 'St. Irenaeus',
    constants.SANCTI_07_05: [],  # 'St. Anthony Mary Zaccariah ',
    constants.SANCTI_07_07: [],  # 'Sts. Cyril & Methodius',
    constants.SANCTI_07_08: [],  # 'St. Elizabeth of Portugal',
    constants.SANCTI_07_10: [],  # 'Seven Holy Brothers and Sts. Rufina & Secunda',
    constants.SANCTI_07_11: [],  # 'St. Pius I',
    constants.SANCTI_07_12: [],  # 'St. John Gualbert',
    constants.SANCTI_07_14: [],  # 'St. Bonaventure',
    constants.SANCTI_07_15: [],  # 'St. Henry the Emperor',
    constants.SANCTI_07_16: [],  # 'Our Lady of Mt. Carmel',
    constants.SANCTI_07_17: [],  # 'St. Alexis',
    constants.SANCTI_07_18: [],  # 'Camillus de Lellis',
    constants.SANCTI_07_19: [],  # 'St. Vincent de Paul',
    constants.SANCTI_07_20: [],  # 'St. Jerome Emiliani',
    constants.SANCTI_07_21: [],  # 'St. Laurence of Brindisi',
    constants.SANCTI_07_22: [],  # 'St. Mary Magdalene',
    constants.SANCTI_07_23: [],  # 'St. Apollinaris',
    constants.SANCTI_07_24: [],  # 'St. Christina',
    constants.SANCTI_07_25: [],  # 'St. James the Greater',
    constants.SANCTI_07_26: [],  # 'St. Anne, Mother of the Blessed Virgin',
    constants.SANCTI_07_27: [],  # 'St. Pantaleon',
    constants.SANCTI_07_28: [],  # 'Sts. Nazarius & Celsus, St. Victor I & St. Innocent I',
    constants.SANCTI_07_29: [],  # 'St. Martha',
    constants.SANCTI_07_30: [],  # 'Sts. Abdon & Sennen',
    constants.SANCTI_07_31: [],  # 'St. Ignatius Loyola',
    constants.SANCTI_08_01: [],  # 'Holy Machabees ',
    constants.SANCTI_08_02: [],  # 'St. Alphonsus Liguori ',
    constants.SANCTI_08_04: [],  # 'St. Dominic',
    constants.SANCTI_08_05: [],  # 'Dedication of the Basilica of St. Mary Major',
    constants.SANCTI_08_06: [],  # 'Transfiguration of Our Lord',
    constants.SANCTI_08_07: [],  # 'St. Cajetan',
    constants.SANCTI_08_08: [],  # 'St. John Mary Vianney',
    constants.SANCTI_08_09: [],  # 'Vigil of St. Lawrence',
    constants.SANCTI_08_10: [],  # 'St. Lawrence',
    constants.SANCTI_08_11: [],  # 'Sts. Tiburtius & Susanna',
    constants.SANCTI_08_12: [],  # 'St. Clare',
    constants.SANCTI_08_13: [],  # 'Sts. Hippolytus & Cassian',
    constants.SANCTI_08_14: [],  # 'Vigil of the Assumption',
    constants.SANCTI_08_15: [],  # 'Assumption of the Blessed Virgin Mary',
    constants.SANCTI_08_16: [],  # 'St. Joachim, Father of the Blessed Virgin',
    constants.SANCTI_08_17: [],  # 'St. Hyacinth',
    constants.SANCTI_08_18: [],  # 'St. Agapitus',
    constants.SANCTI_08_19: [],  # 'St. John Eudes',
    constants.SANCTI_08_20: [],  # 'St. Bernard of Clairvaux',
    constants.SANCTI_08_21: [],  # 'St. Jane Frances de Chantal',
    constants.SANCTI_08_22: [],  # 'Immaculate Heart of Mary',
    constants.SANCTI_08_23: [],  # 'St. Philip Benizi',
    constants.SANCTI_08_24: [],  # 'St. Bartholomew',
    constants.SANCTI_08_25: [],  # 'St. Louis IX',
    constants.SANCTI_08_26: [],  # 'St. Zephyrinus',
    constants.SANCTI_08_27: [],  # 'St. Joseph Calasance',
    constants.SANCTI_08_28: [],  # 'St. Augustine',
    constants.SANCTI_08_29: [],  # 'Beheading of St. John the Baptist',
    constants.SANCTI_08_30: [],  # 'St. Rose of Lima',
    constants.SANCTI_08_31: [],  # 'St. Raymond Nonnatus',
    constants.SANCTI_09_01: [],  # 'St. Giles',
    constants.SANCTI_09_02: [],  # 'St. Stephen of Hungary',
    constants.SANCTI_09_03: [],  # 'St. Pius X',
    constants.SANCTI_09_05: [],  # 'St. Lawrence Justinian ',
    constants.SANCTI_09_08: [],  # 'Nativity of the Blessed Virgin Mary',
    constants.SANCTI_09_09: [],  # 'St. Gorgonius',
    constants.SANCTI_09_10: [],  # 'St. Nicholas of Tolentino',
    constants.SANCTI_09_11: [],  # 'Sts. Protus & Hyacinth',
    constants.SANCTI_09_12: [],  # 'Most Holy Name of Mary',
    constants.SANCTI_09_14: [],  # 'Exaltation of the Holy Cross',
    constants.SANCTI_09_15: [],  # 'Seven Sorrows of the Blessed Virgin Mary',
    constants.SANCTI_09_16: [],  # 'Sts. Cornelius & Cyprian',
    constants.SANCTI_09_17: [],  # 'Stigmata of St. Francis',
    constants.SANCTI_09_18: [],  # 'St. Joseph of Cupertino',
    constants.SANCTI_09_19: [],  # 'St. Januarius & Companions',
    constants.SANCTI_09_20: [],  # 'Sts. Eustace & Companions',
    constants.SANCTI_09_21: [],  # 'St. Matthew',
    constants.SANCTI_09_22: [],  # 'St. Thomas of Villanova',
    constants.SANCTI_09_23: [],  # 'St. Linus',
    constants.SANCTI_09_24: [],  # 'Our Lady of Ransom',
    constants.SANCTI_09_26: [],  # 'Sts. Cyprian & Justina ',
    constants.SANCTI_09_27: [],  # 'Sts. Cosmas & Damian',
    constants.SANCTI_09_28: [],  # 'St. Wenceslaus',
    constants.SANCTI_09_29: [],  # 'Dedication of St. Michael the Archangel',
    constants.SANCTI_09_30: [],  # 'St. Jerome',
    constants.SANCTI_10_01: [],  # 'St. Remigius',
    constants.SANCTI_10_02: [],  # 'Holy Guardian Angels',
    constants.SANCTI_10_03: [],  # 'St. Theresa of the Infant Jesus',
    constants.SANCTI_10_04: [],  # 'St. Francis of Assisi ',
    constants.SANCTI_10_05: [],  # 'St. Placid & Companions ',
    constants.SANCTI_10_06: [],  # 'St. Bruno',
    constants.SANCTI_10_07: [],  # 'Our Lady of the Rosary',
    constants.SANCTI_10_08: [],  # 'St. Bridget of Sweden',
    constants.SANCTI_10_09: [],  # 'St. John Leonardi',
    constants.SANCTI_10_10: [],  # 'St. Francis Borgia',
    constants.SANCTI_10_11: [],  # 'Maternity of the Blessed Virgin Mary',
    constants.SANCTI_10_13: [],  # 'St. Edward',
    constants.SANCTI_10_14: [],  # 'St. Callistus I',
    constants.SANCTI_10_15: [],  # 'St. Teresa of Avila',
    constants.SANCTI_10_16: [],  # 'St. Hedwig ',
    constants.SANCTI_10_17: [],  # 'St. Margaret Mary Alacoque',
    constants.SANCTI_10_18: [],  # 'St. Luke the Evangelist',
    constants.SANCTI_10_19: [],  # 'St. Peter of Alcantara',
    constants.SANCTI_10_20: [],  # 'St. John Cantius',
    constants.SANCTI_10_21: [],  # 'St. Hilarion ',
    constants.SANCTI_10_23: [],  # 'St. Anthony Mary Claret',
    constants.SANCTI_10_24: [],  # 'St. Raphael the Archangel',
    constants.SANCTI_10_25: [],  # 'Sts. Chrysanthus & Daria',
    constants.SANCTI_10_28: [],  # 'Sts. Simon & Jude',
    constants.SANCTI_11_01: [],  # 'All Saints',
    constants.SANCTI_11_02_1: [],  # 'Commemoration of All Souls',
    constants.SANCTI_11_02_2: [],  # 'Commemoration of All Souls – Second Mass',
    constants.SANCTI_11_02_3: [],  # 'Commemoration of All Souls – Third Mass',
    constants.SANCTI_11_04: [],  # 'St. Charles Borromeo ',
    constants.SANCTI_11_08: [],  # 'Four Holy Crowned Martyrs',
    constants.SANCTI_11_09: [],  # 'Dedication of the Archbasilica of Our Holy Savior',
    constants.SANCTI_11_10: [],  # 'St. Andrew Avellino',
    constants.SANCTI_11_11: [],  # 'St. Martin of Tours',
    constants.SANCTI_11_12: [],  # 'St. Martin I',
    constants.SANCTI_11_13: [],  # 'St. Didacus',
    constants.SANCTI_11_14: [],  # 'St. Josaphat',
    constants.SANCTI_11_15: [],  # 'St. Albert the Great',
    constants.SANCTI_11_16: [],  # 'St. Gertrude the Great',
    constants.SANCTI_11_17: [],  # 'St. Gregory the Wonderworker',
    constants.SANCTI_11_18: [],  # 'Dedication of the Basilicas of Sts. Peter & Paul',
    constants.SANCTI_11_19: [],  # 'St. Elizabeth of Hungary',
    constants.SANCTI_11_20: [],  # 'St. Felix of Valois',
    constants.SANCTI_11_21: [],  # 'Presentation of the Blessed Virgin Mary',
    constants.SANCTI_11_22: [],  # 'St. Cecilia',
    constants.SANCTI_11_23: [],  # 'St. Clement I',
    constants.SANCTI_11_24: [],  # 'St. John of the Cross',
    constants.SANCTI_11_25: [],  # 'St. Catherine of Alexandria',
    constants.SANCTI_11_26: [],  # 'St. Sylvester',
    constants.SANCTI_11_29: [],  # 'St. Saturninus',
    constants.SANCTI_11_30: [],  # 'St. Andrew',
    constants.SANCTI_12_02: [],  # 'St. Vivian',
    constants.SANCTI_12_03: [],  # 'St. Francis Xavier ',
    constants.SANCTI_12_04: [],  # 'St. Peter Chrysologus',
    constants.SANCTI_12_05: [],  # 'St. Sabbas',
    constants.SANCTI_12_06: [],  # 'St. Nicholas ',
    constants.SANCTI_12_07: [],  # 'St. Ambrose ',
    constants.SANCTI_12_08: [],  # 'Immaculate Conception of the Blessed Virgin Mary',
    constants.SANCTI_12_10: [],  # 'St. Melchiades',
    constants.SANCTI_12_11: [],  # 'St. Damasus I',
    constants.SANCTI_12_13: [],  # 'St. Lucy',
    constants.SANCTI_12_16: [],  # 'St. Eusebius',
    constants.SANCTI_12_21: [],  # 'St. Thomas',
    constants.SANCTI_12_24: [],  # 'Vigil of Christmas',
    constants.SANCTI_12_25_1: [],  # 'The Nativity of Our Lord',
    constants.SANCTI_12_25_2: [],  # 'The Nativity of Our Lord – Morning Mass',
    constants.SANCTI_12_25_3: [],  # 'The Nativity of Our Lord – Day Mass',
    constants.SANCTI_12_26: [],  # 'St. Stephen',
    constants.SANCTI_12_27: [],  # 'St. John the Evangelist',
    constants.SANCTI_12_28: [],  # 'Holy Innocents',
    constants.SANCTI_12_29: [],  # 'St. Thomas Becket',
    constants.SANCTI_12_31: [],  # 'St. Silvester',
    constants.VOTIVE_ANGELS: [],  # 'Holy Angels',
    constants.VOTIVE_JOSEPH: [],  # 'St. Joseph',
    constants.VOTIVE_JESUSETERNALPRIEST: [],  # 'Our Lord Jesus Christ, Supreme and Eternal Priest',
    constants.VOTIVE_PENT01_0: [],  # 'Most Holy Trinity',
    constants.VOTIVE_PENT02_5: [],  # 'Sacred Heart of Jesus',
    constants.VOTIVE_08_22: [],  # 'Immaculate Heart of Mary',
    constants.VOTIVE_MORTALITATIS: [],  # 'Tempore Mortalitatis'
}
